name: Amazon Scraper

on:
  workflow_dispatch:  # Sadece elle tetiklenir

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
      - name: Kod deposunu çek
        uses: actions/checkout@v3

      - name: Python ortamını kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Bağımlılıkları yükle
        run: |
          pip install -r requirements.txt

      - name: Scraper'ı çalıştır
        run: python amazon_moda.py
