name: Amazon Scraper

on:
  schedule:
    - cron: '*/5 * * * *'  # Her 5 dakikada bir
  workflow_dispatch:       # Manuel tetikleme için

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Kod deposunu çek
        uses: actions/checkout@v3

      - name: Python ortamını kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Bağımlılıkları yükle
        run: |
          pip install -r requirements.txt

      - name: Scraper'ı çalıştır
        run: python amazon_moda.py
